local store = require("intentdiff.comments.store")
local storage = require("intentdiff.comments.storage")
local marks = require("intentdiff.comments.marks")
local config = require("intentdiff.config")

describe("posted state", function()
  it("stamps only the comments handed to it and fires one change", function()
    local st = store.new()
    local changes = 0
    st.on_change(function() changes = changes + 1 end)
    local a = st.add({ file = "a.ts", line = 1, side = "new", type = "note", text = "a" })
    local b = st.add({ file = "b.ts", line = 1, side = "new", type = "note", text = "b" })
    changes = 0
    st.mark_posted({ a }, { service = "github", target = "123", url = "u", at = 1 })
    assert.equals(1, changes)
    assert.equals("123", a.posted.target)
    assert.is_nil(b.posted)
  end)

  it("lists only unposted comments", function()
    local st = store.new()
    local a = st.add({ file = "a.ts", line = 1, side = "new", type = "note", text = "a" })
    st.add({ file = "b.ts", line = 1, side = "new", type = "note", text = "b" })
    st.mark_posted({ a }, { service = "github", target = "123", url = "u", at = 1 })
    local left = st.unposted()
    assert.equals(1, #left)
    assert.equals("b", left[1].text)
  end)

  it("survives a save and load round trip", function()
    config.setup({ cache_dir = vim.fn.tempname() })
    local key = "posted-round-trip"
    local st = store.new()
    st.attach(key)
    local a = st.add({ file = "a.ts", line = 1, side = "new", type = "note", text = "a" })
    st.mark_posted({ a }, { service = "github", target = "123", url = "u", at = 7 })
    local reloaded = storage.load(key)
    assert.equals(1, #reloaded)
    assert.equals("github", reloaded[1].posted.service)
    assert.equals(7, reloaded[1].posted.at)
    storage.clear(key)
    config.setup({})
  end)

  it("loads an older store with no posted field as unposted", function()
    config.setup({ cache_dir = vim.fn.tempname() })
    local key = "legacy-store"
    storage.save(key, { { file = "a.ts", line = 1, side = "new", type = "note", text = "a" } })
    local st = store.new()
    st.attach(key)
    assert.equals(1, #st.unposted())
    storage.clear(key)
    config.setup({})
  end)

  it("does not clear the stamp when a posted comment is edited", function()
    local st = store.new()
    local a = st.add({ file = "a.ts", line = 1, side = "new", type = "note", text = "a" })
    st.mark_posted({ a }, { service = "github", target = "123", url = "u", at = 1 })
    st.update(a, "issue", "edited text")
    assert.is_not_nil(a.posted)
    assert.equals("123", a.posted.target)
  end)

  it("marks a posted box's header without changing an unposted one", function()
    local plain = marks.build_box("hi", "Issue", "Hl")
    assert.is_truthy(plain[1][1][1]:match("%[ISSUE%]"))
    assert.is_nil(plain[1][1][1]:match("POSTED"))
    local posted = marks.build_box("hi", "Issue", "Hl", { posted = true })
    assert.is_truthy(posted[1][1][1]:match("%[ISSUE · POSTED%]"))
    -- Widening the header must not break the box: every line the same width.
    local width = vim.fn.strdisplaywidth(posted[1][1][1])
    for _, line in ipairs(posted) do
      assert.equals(width, vim.fn.strdisplaywidth(line[1][1]))
    end
  end)
end)
