describe("config", function()
  it("merges user opts over defaults", function()
    local config = require("intentdiff.config")
    config.setup({ provider_opts = { model = "sonnet" }, sidebar_width = 50 })
    assert.equals("sonnet", config.options.provider_opts.model)
    assert.equals("claude", config.options.provider_opts.cmd) -- default preserved
    assert.equals(50, config.options.sidebar_width)
    assert.equals(180000, config.options.provider_opts.timeout_ms)
  end)

  it("setup twice starts from defaults, not previous merge", function()
    local config = require("intentdiff.config")
    config.setup({ sidebar_width = 50 })
    config.setup({})
    assert.equals(40, config.options.sidebar_width)
  end)

  it("default provider timeout is 180000ms", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.equals(180000, config.options.provider_opts.timeout_ms)
  end)

  it("auto_open defaults to true and can be turned off", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.equals(true, config.options.auto_open)
    config.setup({ auto_open = false })
    assert.equals(false, config.options.auto_open)
  end)
end)

describe("config UX pass defaults", function()
  it("defaults added_file_split and raises max_hunks", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.is_true(config.options.added_file_split.enabled)
    assert.equals(60, config.options.added_file_split.min_lines)
    assert.equals(40, config.options.added_file_split.target_lines)
    assert.equals(600, config.options.max_hunks)
  end)
end)

describe("config sidebar defaults", function()
  it("widens the sidebar and enables icons", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.equals(40, config.options.sidebar_width)
    assert.is_true(config.options.icons)
  end)
end)

describe("config navigation defaults", function()
  it("opens files on hover by default", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.is_true(config.options.preview.hover_opens_files)
  end)
end)

describe("config keymaps", function()
  local config = require("intentdiff.config")

  it("namespaces keymaps by surface, matching codediff's defaults", function()
    config.setup({})
    -- Same lhs codediff binds to keymaps.view.toggle_explorer: the sidebar is
    -- that explorer's counterpart.
    assert.equals("<leader>b", config.options.keymaps.view.toggle_sidebar)
    assert.equals("g?", config.options.keymaps.view.show_help)
    assert.equals("R", config.options.keymaps.sidebar.reclassify)
    -- zA is codediff's fold_toggle_recursive, NOT the old expand/collapse-all.
    assert.equals("zA", config.options.keymaps.sidebar.fold_toggle_recursive)
    assert.equals("zR", config.options.keymaps.sidebar.fold_open_all)
    assert.equals("zM", config.options.keymaps.sidebar.fold_close_all)
    assert.is_false(config.options.keymaps.sidebar.fold_toggle_all)
  end)

  it("keeps h/l as aliases of the fold open/close keys", function()
    config.setup({})
    assert.same({ "zo", "l" }, config.options.keymaps.sidebar.fold_open)
    assert.same({ "zc", "h" }, config.options.keymaps.sidebar.fold_close)
  end)

  it("lets a keymap be disabled with false", function()
    config.setup({ keymaps = { sidebar = { fold_toggle = false } } })
    assert.is_false(config.options.keymaps.sidebar.fold_toggle)
    -- Its neighbours survive: a surface override merges, it does not replace.
    assert.equals("zA", config.options.keymaps.sidebar.fold_toggle_recursive)
  end)

  it("replaces a list-valued action outright instead of merging indices", function()
    -- vim.tbl_deep_extend would leave "l" behind at index 2, making the
    -- default alias impossible to drop.
    config.setup({ keymaps = { sidebar = { fold_open = { "zo" } } } })
    assert.same({ "zo" }, config.options.keymaps.sidebar.fold_open)
  end)

  it("migrates the pre-namespacing flat keys", function()
    config.setup({ keymaps = { toggle_sidebar = "<leader>gVt", toggle_all = "zA" } })
    assert.equals("<leader>gVt", config.options.keymaps.view.toggle_sidebar)
    assert.equals("zA", config.options.keymaps.sidebar.fold_toggle_all)
  end)

  it("lets an explicit surface win over the migration shim", function()
    config.setup({
      keymaps = { toggle_sidebar = "<leader>gVt", view = { toggle_sidebar = "<leader>x" } },
    })
    assert.equals("<leader>x", config.options.keymaps.view.toggle_sidebar)
  end)

  it("does not leak keymaps between setup calls", function()
    config.setup({ keymaps = { sidebar = { reclassify = "gr" } } })
    config.setup({})
    assert.equals("R", config.options.keymaps.sidebar.reclassify)
  end)
end)
describe("config keymap isolation", function()
  it("does not let an in-place mutation reach the defaults", function()
    local config = require("intentdiff.config")
    config.setup({})
    table.insert(config.options.keymaps.sidebar.fold_open, "zzz")
    config.setup({})
    assert.same({ "zo", "l" }, config.options.keymaps.sidebar.fold_open)
  end)
end)
