describe("config", function()
  it("merges user opts over defaults", function()
    local config = require("intentdiff.config")
    config.setup({ provider_opts = { model = "sonnet" }, sidebar_width = 50 })
    assert.equals("sonnet", config.options.provider_opts.model)
    assert.equals("claude", config.options.provider_opts.cmd) -- default preserved
    assert.equals(50, config.options.sidebar_width)
    assert.equals(180000, config.options.provider_opts.timeout_ms)
  end)

  it("setup twice starts from defaults, not previous merge", function()
    local config = require("intentdiff.config")
    config.setup({ sidebar_width = 50 })
    config.setup({})
    assert.equals(40, config.options.sidebar_width)
  end)

  it("default provider timeout is 180000ms", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.equals(180000, config.options.provider_opts.timeout_ms)
  end)

  it("auto_open defaults to true and can be turned off", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.equals(true, config.options.auto_open)
    config.setup({ auto_open = false })
    assert.equals(false, config.options.auto_open)
  end)
end)

describe("config UX pass defaults", function()
  it("defaults added_file_split and raises max_hunks", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.is_true(config.options.added_file_split.enabled)
    assert.equals(60, config.options.added_file_split.min_lines)
    assert.equals(40, config.options.added_file_split.target_lines)
    assert.equals(600, config.options.max_hunks)
  end)
end)

describe("config sidebar defaults", function()
  it("widens the sidebar and enables icons", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.equals(40, config.options.sidebar_width)
    assert.is_true(config.options.icons)
  end)
end)

describe("config navigation defaults", function()
  it("opens files on hover by default", function()
    local config = require("intentdiff.config")
    config.setup({})
    assert.is_true(config.options.preview.hover_opens_files)
  end)
end)
